version: '3.3'
networks:
  container-connect:
    external: false
services:
  mongo:
    volumes:
      - '~/home/ec2-user/django-mongo/mongo-database:/data/db'
    networks:
      - container-connect
    container_name: mongo
    image: 'mongo:latest'
  mongo-express:
    networks:
      - container-connect
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - 8081:8081
    image: mongo-express
  flask-app:
    build: .
    command: python -u app.py
    environment:
      - APP_ENV='prod'
      - APP_DEBUG='False'
      - APP_PORT=5000
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - container-connect
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 5000:5000
    image: flask-app
